name: naija-estates
favicon: null
layout_spectrum: 0.35644
typography_spectrum: 0.65346
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d89e5e'
    - '#b16d2c'
    - '#270b08'
    - '#f6d6a3'
    - '#fefefe'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
