typography_spectrum: 0.65346
content_rating:
  adult: false
color:
  brandColors:
    - '#d89e5e'
    - '#b16d2c'
    - '#270b08'
    - '#f6d6a3'
    - '#fefefe'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.625
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.26485
analytics:
  google: null
  facebook: null
  twitter: null
logo: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/c2c935be-9cd4-4334-9205-e9ac99ceab24.jpg'
name: naija-estates
cta:
  domain: null
  bucket: null
  version: null
favicon: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/938c3579-0fd2-4bbf-8794-4fe6db0f29a9.jpg'
purpose: []
