name: naija-estates
favicon: null
layout_spectrum: 0.7137359899934381
typography_spectrum: 0.2180638532154262
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9375
  lightness: 0.028647079598158598
  saturation: 0.5951500223018229
  rhythmicContrast: 0.9747132044285536
purpose: []
