typography_spectrum: 0.022595246555283666
content_rating:
  adult: false
color:
  brandColors:
    - '#FFFFFF'
    - '#960C0A'
    - '#E8C8C9'
    - '#B04346'
    - '#D59D9C'
  brandStrength: 0.3838215242139995
  lightness: 0.27324990229681134
  saturation: 0.6072125937789679
  rhythmicContrast: 0.039959340589120984
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7712733678054065
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c2c935be-9cd4-4334-9205-e9ac99ceab24.jpg
name: Nigeria property news
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About us
    id: 2a09a4e1-5d86-4a34-856a-6091e9a669b2
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/938c3579-0fd2-4bbf-8794-4fe6db0f29a9.jpg
title: ''
purpose: []
