name: naija-estates
favicon: null
layout_spectrum: 0
typography_spectrum: 0.85644
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3080c5'
    - '#fbecd7'
    - '#353630'
    - '#8e9c47'
    - '#a75432'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
