name: naija-estates
favicon: null
layout_spectrum: 0.2720366809517145
typography_spectrum: 0.65346
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#703030'
    - '#2F343B'
    - '#7E827A'
    - '#E3CDA4'
    - '#C77966'
  brandStrength: 0.9348082260694355
  lightness: 0.5043059983290732
  saturation: 0.839885544963181
  rhythmicContrast: 0.07179206050932407
purpose: []
